### ISSUE TITLE
Move inline backlink quotes to the bottom of post div

### ISSUE THREAD

**Issue by shrx** [ccd0/4chan-x#101]
Is it possible to move inline backlink quotes to the bottom of the post div, so they're below the post's content instead of on top of it?

**Comment by saxamaphone69** [comment]
For reference, here is what it looks on mobile (both visually and the HTML):

![backlinks-to-bottom](https://cloud.githubusercontent.com/assets/877480/25460720/64637d38-2b28-11e7-89cc-1793616e0f85.png)

however this doesn't exactly transfer well when on desktop:

![bottom-backlink-proof](https://cloud.githubusercontent.com/assets/877480/25460781/aaf5082a-2b28-11e7-97df-79a5fac6f93a.png)

a) On mobile, backlinks do not show on OP, so these would need to be styled specifically for OP (perhaps they use the reply background colour instead)
b) With the background, I had to remove the default padding on posts so that the background is flush to the edges. I think it looks visually better on mobile because all posts are 100% width, and then this causes all posts to lose their padding.

Alternatively, here it is without any backgrounds or padding-removal to posts (which the user could then create Custom CSS for, where they add a background and what not).

![bottom-backlink-proof-1](https://cloud.githubusercontent.com/assets/877480/25460985/c37a41fc-2b29-11e7-97e2-433db9fb34e0.png)

This was done by changing [this part](https://github.com/ccd0/4chan-x/blob/master/src/Quotelinks/QuoteBacklink.coffee#L58) of the code (in JS though not Coffee) to something like
```coffee
if Conf['Reposition Backlinks']
   $.add @nodes.post, container
else
  $.add @nodes.info, container
```
Although not sure if the reference a few lines above that would need to be changed as well. An extra class should probably also be added to `html` that allows the backlink container to be styled separately. (`:root.bottom-backlinks .post { padding: 0; } :root.bottom-backlinks .container { background-color: blue; }` sort of thing)

**Comment by ccd0** [comment]
Requested again in #1469

**Comment by saxamaphone69** [comment]
Okay, so I think I'm willing to put together a PR for this (finally). Just need your opinion and guidance @ccd0.

As mentioned previously, here is what I changed in the compiled JS.

```js
'Quote Links': {
  'Quote Backlinks': [true, 'Add quote backlinks.'],
  'Reposition Backlinks': [true, 'Reposition backlinks to the bottom of posts.', 1],
  'OP Backlinks': [true, 'Add backlinks to the OP.', 1],
  'Quote Inlining': [true, 'Inline quoted post on click.'],
```

Add a specific option to reposition backlinks as a sub-option (re-position? reposition? simply "move backlinks"?)

```js
secondNode: function() {
  var container;
  if (Conf['Reposition Backlinks']) {
    $.addClass(doc, 'bottom-backlinks');
  }
```

Add a class on `html` to specifically target `.container`.

```js
  container = QuoteBacklink.getContainer(this.fullID);
  this.nodes.backlinkContainer = container;
  if (Conf['Reposition Backlinks']) {
    return $.add(this.nodes.post, container);
  } else {
    return $.add(this.nodes.info, container);
  }
},
getContainer: function(id) {
```

And as previously posted, the code which chooses where the `container` is created, depending on the setting.

Now, on vanilla 4chan and 4chan X, you'll see that the unstyled `.container` when at the bottom is a bit visually jarring (imo).

![examples-3](https://user-images.githubusercontent.com/877480/31859436-d73bd682-b757-11e7-9b8a-b694bf8d8a8c.jpg)

So, with the addition of:

```css
:root.bottom-backlinks .container {
  display: block;
}

:root.bottom-backlinks .backlink {
  font-size: 90%;
}
```

And, personally, I think a `clear: both;` can look a tad nicer (in some cases, where in some cases it might look better without it, as it depends on the post contents).

![examples-1](https://user-images.githubusercontent.com/877480/31859633-1bdce90a-b75a-11e7-82ed-a75088423e39.jpg)

So after that long winded post, what is your opinion on the visual side of things? And, given what is being changed on the code side of things, should I be looking anywhere else to make changes? Changing those specific lines does work (newly created backlinks are inserted into the existing container, as opposed 2 containers being created).

If it sounds okay, I'll attempt a formal PR with actual changes as opposed to theorised changes in compiled JS.

**Comment by ccd0** [comment]
> `'Reposition Backlinks': [true, 'Reposition backlinks to the bottom of posts.', 1]`

"Reposition" isn't right because that's where we're putting them in the first place. I would call it something like "Bottom Backlinks" with a description like "Place backlinks at the bottom of posts."

The `true` part turns the option on by default. It might be a good idea to turn it on by default at some point in the future, depending on how well it works in practice, but not until it's better tested.

Other than those issues, it looks right.

> what is your opinion on the visual side of things?

The right side of your last picture looks good enough for a start. We'll probably end up tweaking things as we go along and get more feedback from users.

> And, given what is being changed on the code side of things, should I be looking anywhere else to make changes?

I'd have to look through the code myself, but the main thing is to make sure that the quotelink-related features work, especially quote previewing and quote inlining, including nesting and un-inlining. In terms of looks, it's also important to check that things look okay for all styles.

**Comment by saxamaphone69** [comment]
You're correct about inlining, as the inlined post gets put as the last child of `.postContainer` as opposed to `.post`, which (I assume) is referenced [here](https://github.com/ccd0/4chan-x/blob/master/src/Quotelinks/QuoteInline.coffee#L51).
