### ISSUE TITLE
Using the chrome extension with tampermonkey running, still activates tampermonkey

### ISSUE THREAD

**Issue by HASJ** [ccd0/4chan-x#1037]
I have the chrome extension for syncing and tampermonkey with other userscripts and every time there's a new post in a thread, the tampermonkey count goes up.
Is this intended? Does it have any impact on performance?
It might be my imagination but the tab seems to get slow when the count is showing 200, 300 or 400+.

**Comment by ccd0** [comment]
If it goes up when you make a new post in the thread, it's due to 4chan X running in the captcha iframe. If it goes up whenever new posts get added by the updater, that's unusual and might be a bug with either 4chan X or Tampermonkey. I didn't notice the latter happening, though.

**Comment by ccd0** [comment]
Is this still happening? It might be an issue with one of the other scripts. What happens if you disable all your Tampermonkey scripts? Is there a specific script causing the problem?

And if it goes up when you make a new post in the thread, it's probably just a script that runs on google.com. If it has performance problems, you might want to try adding the captcha frame URL as a user exclude to that script.
