### ISSUE TITLE
4chan-x catalog improvements and other

### ISSUE THREAD

**Issue by broski93** [ccd0/4chan-x#1101]
I've used 4chan-x for a while now, and first of all I wanted to thank you for your work, this extension has improved my browsing experience a lot.
That said, I have a few suggestions to make. I don't know if they should be put in different issues, I literally registered this account minutes ago. If I'm doing something wrong, sorry for the bother.
1-When using 4chan-x catalog, if I hover the mouse pointer on a thread, I don't get any info like I used to with the native 4chan, like OP info, last reply and so on. Would this be implementable?
2-Time passed since a post is not always exact. For example, instead of saying "2 hours and X minutes ago" it simply says "2 hours" when I hover the pointer on the timestamp.
3-IP counter. I have enabled the function that marks the new IPs in a thread (IP number after the poster's name), but I've found that sometimes when the page is refreshed, they disappear.
4-Highlight threads in 4chan-x catalog. Depending on which theme is used, the color is different, and cannot be changed. I wanted to have a red highlight instead of the blue one when using the "tomorrow" theme, and I had to modify the script to change it. An option to choose the color would be nice, I think.
5-Would it be possible to implement a sage indicator? Something that lets you know if a user saged their post.
That's all. Sorry again if I did something wrong, very likely since it's my first post ever here.

**Comment by ccd0** [comment]
> That said, I have a few suggestions to make. I don't know if they should be put in different issues, I literally registered this account minutes ago. If I'm doing something wrong, sorry for the bother.

They should be, and some belong in existing issues. I'll separate them, but please make separate issues in the future, and check for existing ones.

>1-When using 4chan-x catalog, if I hover the mouse pointer on a thread, I don't get any info like I used to with the native 4chan, like OP info, last reply and so on. Would this be implementable?

This is #241. I'm working on adding this info, but I don't think I'm going to do it the same way as native. There's a screenshot of how it looks so far at https://boards.4chan.org/qa/thread/688904#p691015.

>2-Time passed since a post is not always exact. For example, instead of saying "2 hours and X minutes ago" it simply says "2 hours" when I hover the pointer on the timestamp.

Splitting this into #1102. It's not going to be exact, but it could round less.

>3-IP counter. I have enabled the function that marks the new IPs in a thread (IP number after the poster's name), but I've found that sometimes when the page is refreshed, they disappear.

Splitting to #1103.

>4-Highlight threads in 4chan-x catalog. Depending on which theme is used, the color is different, and cannot be changed. I wanted to have a red highlight instead of the blue one when using the "tomorrow" theme, and I had to modify the script to change it. An option to choose the color would be nice, I think.

This you can do with custom CSS. Currently what you'd need to add is
`.catalog-thread.watched .catalog-thumb, .catalog-thread.watched .werkTyme-filename {border-color: red !important;}`
but this will likely be changing soon with the catalog changes.

That said, maybe the default should be changed to red? The blue doesn't stand out well. Moving this discussion into https://github.com/ccd0/4chan-x/issues/489#issuecomment-249281943.

Also, if you want to have a GUI for changing colors and stuff instead of doing custom CSS, you might want to try [StyleChan](https://github.com/nebukazar/StyleChan) / [OneeChan](https://github.com/nebukazar/OneeChan).

>5-Would it be possible to implement a sage indicator? Something that lets you know if a user saged their post.

It's possible, although it wouldn't be 100% reliable. Splitting this feature request into #1104.

**Comment by ccd0** [comment]
Highlight color issue moved to #1175.
