### ISSUE TITLE
4chan X requires new permissions 

### ISSUE THREAD

**Issue by Temcoin** [ccd0/4chan-x#1159]
4chan X requires new permissions
Read and change your data on a number of websites

a number of websites?

Why is this update needing new permissions?

**Comment by memeg0d** [comment]
Interested in this as well, not re-enabling until we're told what's up

**Comment by th4tirishguy** [comment]
These are the websites that it requires permissions for
a.4cdn.org
i.4cdn.org
boards.4chan.org
is.4chan.org
sys.4chan.org
www.4chan.org
www.google.com

Only new one is
is.4chan.org

**Comment by Temcoin** [comment]
Thanks. 
Do you know why it needs access to google.com?

**Comment by ccd0** [comment]
This is the same prompt you got when you installed the thing, only difference is the addition of the new image server is.4chan.org so that features like 404 redirect work the same on those as on images on i.4cdn.org.

google.com is on the list because of the captcha; it's needed for things like filling out the image version with the keyboard to work.
