### ISSUE TITLE
Deleting file when creating new thread wipes thread content

### ISSUE THREAD

**Issue by DarkDibblez** [ccd0/4chan-x#1186]
Reproduce:
Type some text in the new thread window
select an invalid file (I used https://media.playstation.com/is/image/SCEA/playstation-4-pro-vertical-product-shot-01-us-07sep16?$TwoColumn_Image$ as an URL in the file window)
Hit delete when the error message pops up about the file type
?????
Thread window gets cleared of all text.

**Comment by ccd0** [comment]
Deleting the post was the indended behavior; since you can have multiple queued posts and not deleting the post would often leave blank posts behind. So either it needs to make it clearer that it's going to do that, or if you think it would be better to delete the post only if the text is blank, we could perhaps change it to do that.

**Comment by DarkDibblez** [comment]
Considering it only references an invalid file with a delete option, yeah it should definitely say "delete post" if it's going to delete the post.

**Comment by ccd0** [comment]
Should say "delete post" now.
