### ISSUE TITLE
Catalog Hover Expand not saving

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1201]
Submitter: Z
Every once in a while the "Catalog Hover Expand" option turns itself off and I'm unsure why

**Comment by ccd0** [comment]
It's toggled by clicking when "Catalog Hover Toggle" is checked.

**Comment by TeffenEllis** [comment]
@ccd0 Unlike other options, Catalog Hover Expand seems to turn itself on and off quite frequently. Is there a way to turn it off permanently? Is this a bug?

Cheers

**Comment by ccd0** [comment]
@TeffenEllis
It's toggled by clicking in the catalog if "Catalog Hover Toggle" is checked.

**Comment by TeffenEllis** [comment]
@ccd0 
I understand the means to toggle the feature. I think bug reports are coming in because toggling the the feature is not persistent.

I believe the desired behavior is that the Catalog Hover Expand remains off indefinitely until the user toggles it back on. That doesn't appear to be the case at the moment.

**Comment by ccd0** [comment]
@TeffenEllis
Can you give steps to reproduce the problem?

**Comment by ccd0** [comment]
Closing, if there's a bug rather than just the expected toggling behavior and you can provide more details, we can reopen and look into it.
