### ISSUE TITLE
Minimum Browser Version Requirements (for CSS)

### ISSUE THREAD

**Issue by saxamaphone69** [ccd0/4chan-x#1314]
I only ask because the CSS contains code such as

 - `-moz-box-sizing` (prefix dropped in 2014, Firefox 29)
 - `-webkit-transform` (prefix dropped in 2014, Chrome 36)
 - `-webkit-transition` (prefix dropped in 2013, Chrome 26)
 - `display: -webkit-flex` (prefix dropped in 2014, Chrome 29)

which could be un-prefixed, however I know this particular fork of 4chan X supports a wide range of browsers.

Depending on which versions this fork supports, CSS Variables have also been supported for a year now (since Chrome 49 and Firefox 31) and could be implemented.

For browsers that don't support CSS variables, perhaps they can load an additional stylesheet containing the code that exists now.

**Comment by ccd0** [comment]
They're listed here:
https://github.com/ccd0/4chan-x/blob/1.13.8.4/package.json#L60

I update them every now and then, but I don't like to do it very often. Usually a few things get reverted back afterwards because somebody was using an old browser or a lagging-behind fork.

Also, there are WebKit-based browsers to consider, although I haven't listed a specific supported version. Some of the `-webkit-` prefixes were actually targeting those.

And if we need to use something that's only present in up-to-date browsers, it's perfectly fine as long as it doesn't break existing features for people on older stuff / forks.

**Comment by saxamaphone69** [comment]
Don't fix what ain't broke; I guess it's probably best just to leave it as is.
