### ISSUE TITLE
Cooldown timer freezing (was: Can't submit new reply if quick reply is opened while still on post cooldown)

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#1323]
If I open the quick reply to begin typing another comment in a thread where I'm still on post cooldown, the reply button becomes stuck at that number of seconds and I have to reload the thread to submit another reply.

**Comment by ccd0** [comment]
Can you check for error messages? And test in a fresh profile?

See https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by EroticSpork** [comment]
Can't replicate the issue outside of my main profile, maybe I'm running too many scripts.

**Comment by zJelly** [comment]
Was having this bug and made a new Firefox profile attempting to fix it, but its resurfaced less than 24 hours later. My browser console lists the following output (when filtered for 4chan-x):

```
00:41:50.906 uncaught exception: unknown (can't convert to string) 1 4chan-X.user.js:4969:7
```
It appears to more often occur when 2 threads are open after middle-clicking a cross-thread link.

**Comment by ccd0** [comment]
@zJelly
Looks like it might be an issue with Greasemonkey
Can you give your Greasemonkey version and check in about:support whether Multiprocess is enabled?

**Comment by ccd0** [comment]
from #1342:
Submitter: James
USERSCRIPT MANAGER --> Greasemonkey (3.10)
BROWSER --> Mozilla Firefox (53.0, 32-bit)
SCRIPTS --> 4chan X (1.13.9.0)

The bug tends to happen when I attempt to post after having recently made another post. The post timer that replaces the SUBMIT button is supposed to countdown, but it stays frozen on a number. For example, the countdown commonly freezes at 59 seconds, and clicking it puts it onto Auto 59 seconds, but changes nothing still. The only clear I have is to refresh the entire page after making a post to avoid a frozen timer on the next post.
Sometimes, I switch a tab while the timer counts down, return, and it's frozen again despite the fact that it was working fine moments before. The most consistent thing about the bug for me is that it always happens when I reply to a post or make a post, forcing me to refresh the page. The bug does not occur on the native extension, and occurs regardless of custom options on 4chan X. Checking the console also brings up no reports.

**Comment by zJelly** [comment]
My Greasemonkey version is 3.10 according to the about:addons page
about:support lists:
```
 Multiprocess Windows 	0/2 (Disabled)
```

**Comment by ccd0** [comment]
I just pushed a workaround; let me know if there are still problems.

**Comment by ccd0** [comment]
From @h633537, https://github.com/ccd0/4chan-x/issues/1342#issuecomment-297899597:
> The timer has frozen on 1 second quite a few times since updating to 1.13.9.2. This is on Firefox 53 64bit.

**Comment by ccd0** [comment]
upstream issue:
https://github.com/greasemonkey/greasemonkey/issues/2503

**Comment by forbjok** [comment]
My 4chan X version is 1.13.8.6 according to the settings dialog.
It should be auto-updating itself.

Greasemonkey is 3.11.

**Comment by Rei1226** [comment]
I'm having the same issue. It'll freeze on 1 second, won't happen every time though, it's kinda rare. No idea what could be causing it.

My 4chan X version is also 1.13.8.6

GreaseMonkey is 3.11 as well.

**Comment by zackultimate** [comment]
Same issue here!

**Comment by PaganJoe** [comment]
Came here to post this but thread already exists for it. Firefox 54, GM 3.11, 4chan x 1.13.8.8

**Comment by ccd0** [comment]
There's not much I can do about this, either use Firefox ESR until this is fixed on Greasemonkey's end or try building Greasemonkey with
https://github.com/greasemonkey/greasemonkey/pull/2507

**Comment by zJelly** [comment]
The "workaround" I settled on was to move to Violentmonkey on Firefox, which is now available as a WebExtension:
https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/
https://github.com/violentmonkey/violentmonkey/releases
4chanX functions as expected, based off a month of using it.

**Comment by forbjok** [comment]
Replacing Greasemonkey with Tampermonkey also fixes this issue.

**Comment by ccd0** [comment]
This should be fixed in the latest version of Greasemonkey. If you're still having any problems, let me know.
