### ISSUE TITLE
Unable to post replies

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1376]
Every time I try to submit a reply the message "Connection error while posting appears"

Clicked the more info section for remedies but didnt get any detailed fix

**Comment by ccd0** [comment]
Did you try the stuff suggested there, and if so, what happened?

**Comment by cantkeepmydickinmypants** [comment]
The message asked me to use the post form. Can't find the "Original Form" link. Would be helpful if you could point out where the "Original Form" is.

The 8 May 2017: If you are having connection errors when posting certain text, it is because of an extra captcha Cloudflare wants you to solve before allowing your post to go through to 4chan. It is not yet integrated correctly with 4chan yet (CORS headers are missing). To make your post go through, you will need to use the post form at the top of the page (click the "[Original Form]" link).

**Comment by cantkeepmydickinmypants** [comment]
I'm including a list of errors I found with the developer function (F12)
Tried disabling adblock but that didnt have any affect. I think it's important to note that the server responded with a "Forbidden access" message when it was requesting permission to post. The complete list is given below



Refused to load the script 'blob:http://boards.4chan.org/87bbcefa-451c-4d79-8bbe-28d17b518fa6' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

(anonymous)
(unknown) 
ad.doubleclick.net/favicon.ico?ad=300x250&ad_box_=1&adnet=1&showad=1&size=250x250 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

core.min.1012.js:1 Refused to load the script 'http://utraffic.engine.adglare.net/?688619547' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org 

http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org 
https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

initAdsAG @ core.min.1012.js:1
core.min.1012.js:1 Refused to load the script 'http://www.google-analytics.com/analytics.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

(anonymous) @ core.min.1012.js:1

a.4cdn.org/co/threads.json?s=ThreadStats Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4429 4chan X failed to load: //a.4cdn.org/co/threads.json?s=ThreadStats

(anonymous) @ chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:4429

(unknown) [Deprecation] 'webkitURL' is deprecated. Please use 'URL' instead.
(anonymous)

3sys.4chan.org/co/post Failed to load resource: the server responded with a status of 403 (Forbidden)

www.gstatic.com/recaptcha/api2/r20170515161201/recaptcha__en.js:380 Uncaught TypeError: Cannot read property 'render' of null
    at Vp (www.gstatic.com/recaptcha/api2/r20170515161201/recaptcha__en.js:380)
    at Np.Hk (www.gstatic.com/recaptcha/api2/r20170515161201/recaptcha__en.js:381)

4sys.4chan.org/co/post Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by ccd0** [comment]
The "[Original Form]" link should be directly underneath the "Start a Thread" or "Reply to Thread" button. Make sure you're not hiding it with Oneechan, your ad blocker, custom CSS. Try posting with the original form, and based on the error you get, that will help you figure out what's wrong.

**Comment by cantkeepmydickinmypants** [comment]
Had to solve a couple of captchas but got through. Thanks a ton, man
