### ISSUE TITLE
Upload failed (only when using extension)

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1396]
Submitter: Anonygyppo
Email: alt.bl-5du5evp@yopmail.com
I keep getting a "Upload failed" error, on whichever board I try to post, with or without an attached image, only when the extension is enabled. I hoped the update might fix it, but it didn't.  I'm using Chrome on Windows 8.1, and I also use uBlock Origin.

**Comment by 7th1rt3en** [comment]
The same thing happens to me even  with every extension disabled except for 4chan-x. I'm on Chrome and Windows 10. At first I thought it was related to Tampermonkey because it had just updated when the problem started but it happens even with it disabled.

**Comment by ccd0** [comment]
Does the original post form work for you?
Can you try disabling "Show Upload Progress"?

**Comment by 7th1rt3en** [comment]
Reinstalled it again, this time with Violentmonkey and have the same issue even after I disable "Show Upload Progress". However, the original form DOES work all of the time.

**Comment by cantkeepmydickinmypants** [comment]
@7th1rt3en Can you tell me how I can access the original form?

**Comment by 7th1rt3en** [comment]
Perhaps the issue is not related to the extension, even thought it started a few days after I started using it. I just started getting the same problem with ALL extensions off, with or without using 4chan pass. So I turned on violentmonkey and 4chan-x and it RESOLVED the issue. I have no clue what is happening but it is frustrating.
