### ISSUE TITLE
Preview of selected file not showing

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1429]
After you select a file, it used to show a preview below the captcha. The box is still there, but it doesn't show the actual image. This feature was especially helpful when pasting a copied image directly into the comment box or when having multiple posts lined up for an image dump thread. I'd be most appreciative if this feature was restored. Thank you!

**Comment by AchtBit** [comment]
I noticed this happening as well. Looking in the console I noticed a line like this for each image loaded into the QR:
`Refused to load the image 'blob:https://boards.4chan.org/464fb882-de68-40ad-ba6e-9566f4c53788' because it violates the following Content Security Policy directive: "default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`
So I tried disabling uBlock temporarily and the previews generated fine.

**Comment by ccd0** [comment]
See #1417.
