### ISSUE TITLE
v1.13.10.5 "Add Board Tips."

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1458]
What did he mean by this? Seriously, I don't understand what this feature is. I don't see any tips anywhere.

**Comment by saxamaphone69** [comment]
Head over to `/qa/`, and you should see a notification pop up telling "new" users that it's not the place to complain to mods.

Once it is dismissed, it won't pop up again.

**Comment by animepony** [comment]
This message on /qa/ is satirical, right? /qa/ is a topicless, unmoderated board in which you can make a thread about anything you would like (worksafe). Sure, /qa/ isn't an effective way to "contact the mods" - But neither is /r9k/, or /g/, or any of the boards. Telling people to go to IRC is wrong, because most of people there are mislead by a meme that is regularly posted and take the IRC as the feedback page. These people only clutter up #4chan. The people that go to IRC for meta issues are just shooed off to the feedback page, and if they persist, are kicked.

**Comment by bakugo** [comment]
Nobody cares about the feedback form either. Bugs I've reported literal years ago are still unfixed.  
The message is just something the mods came up with to kill the last place where you could actually talk about the site, and it succeeded because now it's just endless anime spam.

**Comment by ccd0** [comment]
@animepony
I'll update the message for clarity, but many people have gotten responses by PMing on IRC.
https://github.com/ccd0/4chan-x/commit/69cdf1f03cb29554e76c3003a18f30273b95754a

@bakugo
Plenty of discussion of the site still goes on. But people who go there to contact the mods should be sent to the actual mods.
