### ISSUE TITLE
adblockers stopping 4chanX from working as Violentmonkey script

### ISSUE THREAD

**Issue by dlfsjdfjodifjsodifjsdo** [ccd0/4chan-x#1546]
ublock origin/adnauseum @ default settings both separately stop 4chanX+violentmonkey from working. They are fully updated. All on firefox 56.0.2 . Had to whitelist 4chan.org for it to work.

however, chromium+chrome store 4chanX+ublock origin does work correctly.

edit: works fine in tampermonkey default

**Comment by GirlsCantKissGirls** [comment]
can confirm ublock origin is blocking it with violent monkey on firefox. all default settings.

**Comment by guicale** [comment]
To fix this without having to whitelist 4chan.org, add `4chan.org 4chan.org * allow` to your uBlock rules.

**Comment by ccd0** [comment]
@dlfsjdfjodifjsodifjsdo
What browser are you using?

**Comment by ccd0** [comment]
Can reproduce with Violentmonkey+Firefox.

Seems to be due to the Easylist filter against `blob:`, just like #1417. The filters in https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions#error-reading-metadata should work (I tested the uBlock one and it worked for me).

By the way, if you're using Violentmonkey because of Firefox 57, there's an [version of Greasemonkey available for it](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/#beta-channel), although older userscripts may need updates before they are compatible with it. 4chan X should work, though.

**Comment by hhiru** [comment]
This is kind of off-topic but I want to report that I have no issues with uBlock+Violentmonkey on Chromium
