### ISSUE TITLE
Thread Watcher Sets All Threads as Archived 

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1579]
Submitter: Anonymous
Email: cloudyday@chiru.no
When refreshing the thread watcher in the catalog, it sets all threads as archived - 
like this https://vgy.me/QIF7pp.png

**Comment by ccd0** [comment]
Could be a temporary issue on 4chan's end as this would be expected if the threads 404. Is it still happening?

4chan X catalog or native catalog? What browser and user script engine are you using? Versions?

**Comment by theanimedelusion** [comment]
Yes, that's what would be expected if the threads 404, but the thread watcher sets all my *active* threads to look like they 404d even when they are still alive - I am still getting this issue.

I don't know what is causing this - I said it may be from refreshing the catalog but it might be from something else as well, I appear to only be getting this problem after visiting the catalog somehow, or maybe switching boards? If I figure it out when exactly it switches my active threads to 404 I will update you. 

Attached are my settings, and another image of what this looks like - that last thread on /vr/ is still active, when I click on it it will change to active with a (0) unread replies again. Those other two are dead (404). 

I am using latest version of 4chan X, firefox 57, and violent monkey. This problem only appeared when I switched from greasemonkey in 56 to violentmonkey in 57. 

[4chan X v1.13.14.8-1510868580930.log](https://github.com/ccd0/4chan-x/files/1480336/4chan.X.v1.13.14.8-1510868580930.log) (changed filename extension to .log to upload)

Before - ![image](https://user-images.githubusercontent.com/18670258/32916000-914fa6e0-cacf-11e7-834a-d04f5029dd99.png) 
After - ![image](https://user-images.githubusercontent.com/18670258/32917597-8d5400b8-cad4-11e7-9c28-69172c293501.png)

**Comment by theanimedelusion** [comment]
Forgot to mention - this doesn't affect archived threads.

pics related - it marks all currently active threads as dead but threads marked as archived are not affected. I can still see red (You)s from archived threads - not so for the fake 404d threads.

https://vgy.me/sL8Gwl.png
https://vgy.me/TKtvOL.png

before and after "waking up" some threads - you can see archived ones are not affected.

As far as I am aware, manually refreshing the thread watcher while on a thread rather than on the catalog has never caused this issue.

**Comment by ccd0** [comment]
Are you using any other extensions? Can you test if it happens with them temporarily disabled?

**Comment by theanimedelusion** [comment]
Sorry for the delay - I hoped that the problem would have just disappeared but it happened again.

I am using Imagus, violentmonkey, HTTPS everywhere, and uBlock origin - I just disabled HTTPS everywhere, I'll update you if it stops happening after some time. 

My issue is that it happens very sporadically. I haven't been able to find out what exactly is causing this - I'll pay better attention to my thread watcher and update you if I can pinpoint what I did to cause it in particular. 
I'm pretty sure somehow this is connected to either switching boards in general or /f/ and /wsg/. Because yesterday I just browsed /g/ and /r9k/, but I just looked at some thread on /wsg/ today, then all my active threads switched to dead. That seems kind of stupid though, doesn't it...?

I've haven't been able to recreate the error consistently. Just switching between boards and refreshing the catalog doesn't do it. But it IS still happening. I am like 90% sure that manually refreshing the thread watcher, either in a thread or on the catalog, cannot cause this to happen - it must be when it automatically refreshes.

it's a really annoying error, because I have to go through and click on all the 404 threads individually to wake them up again... any idea what might be causing this on my end? Have any other violentmonkey users been getting strange issues?

Oh, also - even if 4chan X thread watcher thinks the thread is 404 it still stores data on it, like if I am OP and (You)s and whatnot. I just "woke up" https://boards.4chan.org/t/thread/780369, I can still see all my (You).

(Another unrelated problem I have for you - new threads can't be posted from quick reply inside a thread for old captcha users, pic related https://vgy.me/I9nWhS.png)

Here's another image of the issue if you want it - 
those /g/, /vr/,and /wsg/ threads are fake dead, those /f/ and/bant/  threads are actually dead, and archived threads are not affected. (made mistake in the OP, said archived, meant dead)
![image](https://user-images.githubusercontent.com/18670258/32989874-96a03b04-ccd3-11e7-916d-3fc65ff828e0.png)

**Comment by ccd0** [comment]
Could it be #1656?

**Comment by theanimedelusion** [comment]
Yep, that's it! 

Shift - C caused this for me 
![image](https://user-images.githubusercontent.com/18670258/32997953-62cd7fc6-cd4b-11e7-8d6d-8dade777f189.png)

and also caused all active threads in my thread watcher to 404.

**Comment by theanimedelusion** [comment]
Yep, the shift-C issue is fixed, it brings me back to the catalog now. 

I never used that keybind before, though, so I am not sure if my thread watcher issue is fixed -  I will let you know if it happens again.

**Comment by ccd0** [comment]
> I never used that keybind before, though, so I am not sure if my thread watcher issue is fixed - I will let you know if it happens again.

It wasn't just that one, it was it and a few others that navigated to other pages.

**Comment by theanimedelusion** [comment]
well I haven't had any issues so far, so I guess it's fixed. Thanks!

(also I have a small feature request, can you add hover for relative post date on /f/?)

**Comment by ccd0** [comment]
In the index, right? (It should already work in threads.) Moving that to another issue #1689 and closing this one.
