### ISSUE TITLE
4chan-X fails to post a comment and gives "You mistyped captcha" error 50% of the time

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1831]
I've noticed that 4chan-X fails to post a comment about 50% of the time now and gives an error that either "Captcha failed" or that "You mistyped captcha". Now that 4chan doesn't even accept v1 captchas, this error is nonsensical. Second time you solve the (horrible, image-based) captcha, it does post. The bug is so annoying that I've had to disable 4chan-X because of it.

Using Chromium, latest version. Captcha Fixes turned on. Force Noscript Captcha turned off.

**Comment by cps104** [comment]
Kind of surprising that it's not happening without 4chan-X. I was getting essentially the same problem both with and without 4chan-X (and on my mobile devices) in Safari for months. What fixed it was deleting both my 4chan _and_ Google cookies. What seemed to cause it to return was jumping around to different IPs. Particularly with my cell phone, and particularly given my cell service provider's IP ranges seem to be permabanned due to illegal activity. Aaaand since Safari seems to share cookies between my devices, I'm guessing that's related. Once I cleared out my Google and 4chan cookies, the captchas started working 100% of the time, and were much easier.

I think on 4chan-X's end the solution might be for the error message to recommend deleting your Google cookies if the problem persists.

**Comment by nonijod** [comment]
What did the trick for me was to disable captcha fixes, didn't have any issues since.

**Comment by siavash119** [comment]
using private mode with all javascript and 4chanX disabled (just regular noscript 4chan posting), I'm getting mistyped captcha 100% of the time. Did 4chan change settings to not allow noscript captcha?
