### ISSUE TITLE
4chan x not working at all anymore (Firefox) 

### ISSUE THREAD

**Issue by Nzash** [ccd0/4chan-x#1968]
Wasn't even on the latest FF version but I just updated and it changed nothing, 4chan x basically doesn't do anything right now and all of its features and changes to the site are missing despite the script being up-to-date and enabled in tampermonkey.

**Comment by sanitysama** [comment]
same problem here. i tried looking through the browser console for JS errors but nothing in there was unusual. tried reinstalling and 4chanx loads and works perfectly fine on its first page load, but try navigating to any page after that and it doesn't load.

strange considering it worked perfectly fine last night, left my browser open overnight as well so nothing should have been able to update. this is likely 4chan's fault.

**Comment by Busimus** [comment]
Same thing is happening to me. It started with appchan-x not working, so I looked for refuge here but the same thing happens to this userscript as well.
The only thing that makes it _sometimes_ work for me is disabling ad block (uBlock Origin). It still only works like 60% of the time, but it's 0% with ad block enabled.

**Comment by sanitysama** [comment]
anon found a solution by adding Content Security Policy to your adblocker blacklist. back to 100% page loads, but this doesn't seem safe. use at your own risk.

> @@||boards.4chan.org^$csp

**Comment by ccd0** [comment]
Looks like they added some new filters to block Hiroyuki's ads, and it's inadvertently blocking 4chan X.
You can also try Greasemonkey if Tampermonkey isn't working.

**Comment by ccd0** [comment]
>You can also try Greasemonkey if Tampermonkey isn't working.

Or Violentmonkey.

**Comment by ccd0** [comment]
relevant:
https://github.com/Tampermonkey/tampermonkey/issues/418
https://github.com/Tampermonkey/tampermonkey/issues/532

**Comment by Nzash** [comment]
Yeah, can confirm it works fine with Violentmonkey. Thanks a lot, screw Tampermonkey then!

**Comment by ccd0** [comment]
It seems they're working on fixing this on Firefox's end:
https://bugzilla.mozilla.org/show_bug.cgi?id=1267027
https://bugzilla.mozilla.org/show_bug.cgi?id=965637

**Comment by PixelEater** [comment]
This is an interesting problem and I'm glad we're partway through solving it. I'd just like to add my tangential observations, at the risk of being a bit redundant.

Both Violentmonkey and Tampermonkey basically require disabling uBlock Origin, otherwise 4chan X is totally disabled. Notably however, on my end at least, Greasemonkey 4.x seems to perform worse with 4chan X compared to Tampermonkey. I have very decent hardware specs. I suppose Greasemonkey hasn't been too good for a while now.  Same issue I noticed months ago, Greasemonkey causes hidden threads to linger for like a second on every page refresh. Mod stickies for instance. I sense general lag as well, none of which I had a hint of with Tampermonkey. I'd love to join the closed source hating bandwagon, but I believe Violentmonkey wasn't peforming well say half a year ago for me. Also it is quite bare of features as I recall. I will give it another shot when actually possible. Meanwhile I hope no possibility is overlooked in getting this fixed for every alternative. Hiro has caused some of the quirkiest conflicts I've ever seen on a highly visited website.

**Comment by BondiBear** [comment]
Can confirm: **Tampermonkey** - broken, **Violentmonkey** - works (for now).

But this cant be a permanent solution!

**Comment by MikeX7** [comment]
Same here, I can get it work by F5ing the page several times but that is quite annoying

**Comment by N3X15** [comment]
Yeah, I wouldn't hold my breath, the issue for fixing the CSP problem is four years old.

**Comment by derjanb** [comment]
> Can confirm: Tampermonkey - broken

Should be fixed at [Tampermonkey BETA](http://tampermonkey.net/index.php?browser=firefox) 4.7.5788

**Comment by PixelEater** [comment]
Alright! I really don't know about anyone else but Tampermonkey loads all aspects of 4chan X much more snappy on my end. The beta version does seem to be working fine again.

**Comment by derjanb** [comment]
Fixed at Tampermonkey (stable) 4.7.5788

**Comment by Gladuin** [comment]
Violentmonkey is broken for me...
