### ISSUE TITLE
Why were so many new connect hosts not directly related to 4chan added in v1.14.3.0?

### ISSUE THREAD

**Issue by PyroDevil** [ccd0/4chan-x#2078]
There were many new hosts added in the v1.14.3.0 release: https://github.com/ccd0/4chan-x/commit/5b154550a520a602093ba057230d9429f18519d7

Like these:
```
// @connect      mayhemydg.github.io
// @connect      archive.4plebs.org
// @connect      archive.nyafuu.org
// @connect      archive.rebeccablacktech.com
// @connect      warosu.org
// @connect      desuarchive.org
// @connect      boards.fireden.net
// @connect      arch.b4k.co
// @connect      archive.b-stats.org
// @connect      archived.moe
// @connect      thebarchive.com
// @connect      archiveofsins.com
// @connect      api.clyp.it
// @connect      api.dailymotion.com
// @connect      api.github.com
// @connect      soundcloud.com
// @connect      vimeo.com
// @connect      www.googleapis.com
```

I searched in the changelog or code for some justification but could not find it. Maybe some notes about this might be nice to have.

**Comment by bakugo** [comment]
Previously, 4chan X connected to these domains (archives, embeddable websites, etc) directly through the page. But recently some adblock filters started blocking all off-site connections on 4chan (due to hiro's extremely intrusive ads) so 4chan X now connects to them from inside the extension itself to bypass this, and this requires the @connect headers which weren't required before.

**Comment by PyroDevil** [comment]
Ok, thanks for the explanation!
