### ISSUE TITLE
DeviantArt filename format has changed

### ISSUE THREAD

**Issue by kargaroc** [ccd0/4chan-x#2237]
```
Old:
<title>_by_<artist>-<random 7 character string>.<extension>

New:
<title>_by_<artist>_<random 7 char string>-<pre/fullview>.<extension>
<title>_by_<artist>_<random 7 char string>.<extension>
<title>-<string of 9 or more digits>.<extension> (looks like its just the last part of a deviantart URI)
```

Removing support for the old name format wouldn't be good though, as there's still gonna be lots of files in the wild that have the old filename format.

**Comment by ccd0** [comment]
When I try to download something from DeviantArt, it looks like the format is the same as before. Do you know what I have to do to get a file in the other formats? Can you link to examples of some of these on 4chan?

**Comment by bakugo** [comment]
It depends on when the image was uploaded, I think, older images still have the old format, recent images have a new format.

Here's an example of a recent image: https://www.deviantart.com/axsens/art/Sword-Maiden-788756151
If you save the image on the page you get this: `sword_maiden_by_axsens_dd1ls53-fullview.jpg`
If you click the download button you get this: `sword_maiden_by_axsens_dd1ls53.jpg`

For larger images, sometimes you'll get `-pre` instead of `-fullview` before expanding them. Some images also don't have the `-fullview`/`-pre` filename on the page, like [this one](https://www.deviantart.com/skfuu/art/LET-IT-GO-LET-IT-GO-788712426), the filename is instead `dd1kuei-6e93955a-3876-4799-aaf0-19acc3a7891f.jpg` which seems to be the image ID followed by a random UUID, and the artist name isn't present (it's not really needed)

These should cover all cases:
```
//www.deviantart.com/gallery/#/d%$1;regexp:/^\w+_by_\w+[-_]d([0-9a-z]{1,7})/
//www.deviantart.com/gallery/#/d%$1;regexp:/^d([0-9a-z]{1,7})-[0-9a-z]{8}-/
```

And some examples of `-fullview` on 4chan: https://desuarchive.org/_/search/filename/%2Afullview/

**Comment by ccd0** [comment]
Thanks for reporting. This should now be fixed.
