### ISSUE TITLE
today started to get various errors

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2378]
Submitter: altoidsbox
Email: klickclack@protonmail.com
when going to a board, i get the error
>Failed to load board configuration. Invalid Data
i looked online, and you responded to people with same problem - you said to disable network service flag in the chrome settings page - 
i did that, but i still get the error - and on top of that, i cant post, it says connection error when posting. ive uninstalled and reinstalled the chrome extension, still nothing - ive restarted chrome and my computer, no dice. 

my email is klickclack@protonmail.com if you have any solutions. thanks - really like this extension

**Comment by ccd0** [comment]
Are you using any other extensions? Try disabling them temporarily to see if there's any conflict with 4chan X. If there's a problem with your ad blocker, try forcing an update of your filter lists.

**Comment by Nekoragi** [comment]
Same thing started happening to me this morning, Chrome updated to Version 76.0.3809.100 (Official Build) (64-bit) and I get "Failed to load board configuration. Invalid Data" error up top no matter what old solution I try, auto-update is dead, I don't know about posting because I'm banned atm lmao.

The #2228 network-service flag is gone, #2321 fix for this doesn't seem to work for me, I'm on latest 4chanx.
#2291 4chanx has access to reading and changing data on all sites in Chrome extensions, still doesn't work.
My uBlock is off on 4chan as well.
Chrome console:
https://i.gyazo.com/e6cefe565699ab8737495b5a907f1a14.png

I'm gonna have to switch to tampermonkey.

**Comment by ccd0** [comment]
This should be fixed now. Switching to Tampermonkey, or even better, using a browser that isn't Chrome, is still a good idea.
