### ISSUE TITLE
New version of noscript appears to block 4chanx

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2464]
Firefox Developer Edition 71.0b5
Noscript 11.0.4 (listed on the mozilla store but not in the noscript changelog, strangely)
Messages in the console "[NoScript] Some script managed to be inserted in the DOM while fetching policy, blocking it.
 (function (NAVIGATOR, OBJECT) {"
Extension often fails to load whether or not I have ublock blocking the extension, and whether or not ublock is off. Noscript being set to allow everything makes no difference, the only remedy is turning it off entirely. 
This may not be fixable from the 4chan-x side, but I figured reporting it here so it could be tracked was a good idea.

**Comment by F0kT** [comment]
Maybe it's something to do with the pvclouds.com domain. Whitelisting it locally in uBlock and allowing it in NoScript seems to enable 4chanX.

**Comment by shinigamichan** [comment]
@F0kT 
No, it doesn't have anything to do with that domain. Turning off uBlock and allowing everything in noscript didn't make a difference. This is just non-deterministic so sometimes it happens to work alright.
See https://github.com/hackademix/noscript/issues/108
It's been fixed in a development version of noscript. Been running 11.05rc2 for a while with no issues.

**Comment by pizzadude** [comment]
It seems fixed now.
