### ISSUE TITLE
Settings won't save

### ISSUE THREAD

**Issue by Juni221** [ccd0/4chan-x#251]
Every time I load a new thread or refresh a page on 4chan, the settings come up as if I haven't set them yet. The newest update won't even let me import settings.

**Comment by LimeHunter7** [comment]
I have the same issue; I'm using Google Chrome in Win8.
When I open any page on 4chan, the 4chanX settings dialog comes up, and it reminds me that it's updated to 1.9.20.5.
In general it doesn't seem that 4chanX's memory is persistent; even though the options for it to are checked, it doesn't remember my place in threads anymore; each time I open a thread, it marks all the posts as new.
Also, in console it gives me this error: "This request exceeds the MAX_SUSTAINED_WRITE_OPERATIONS_PER_MINUTE quota."

**Comment by ccd0** [comment]
What version of Chrome are you using?  Does it happen anymore as of Chrome 40?  If so, what is the current error message?

**Comment by LimeHunter7** [comment]
Chrome version is Version "39.0.2171.99 m". Also, since I left the page open about 8 hours ago,the same error has occurred 1,296 times according to the console, and it is traced back to "extensions", so there's that.
EDIT: Okay, updated to Chrome 40, and I the problem seems fixed. Chrome must have been restricting the extension somehow.
Thanks!

**Comment by ccd0** [comment]
It was running into the quotas on synced storage changes, but the particular limit it was running into has been removed as of Chrome 40:

https://developer.chrome.com/extensions/storage#property-sync-MAX_SUSTAINED_WRITE_OPERATIONS_PER_MINUTE
