### ISSUE TITLE
Custom board bar when I press [+]?

### ISSUE THREAD

**Issue by zackultimate** [ccd0/4chan-x#2534]
https://i.imgur.com/nhkwLGm.jpg

Is there a way to customize this so only few boards appear?

**Comment by Vulgaris-Viridis** [comment]
Click the drop-down arrow next to the wrench and select/check _Header-->Custom Board Navigation_; 
Click _'Edit custom board navigation'_ bellow and just add boards you'd like to appear in your navibar separated with space. 
(eg: _biz fit g wsr_ etc..)

To open boards in catalog view instead of index/thread view add '-catalog' to the board abbreviation. 
 (eg: _biz-catalog fit-catalog_ etc..)
