### ISSUE TITLE
Captchas now working?

### ISSUE THREAD

**Issue by zackultimate** [ccd0/4chan-x#2668]
As title says.

Captcha doesn't work anymore for me with 4chan X. Works fine if I disable it.

**Comment by qwertyashes** [comment]
Can confirm, the captcha box displays the message "Sorry, something went wrong. Please try reloading the page".
This goes for both BETA and release branches of 4chanX.
Its not related to noscript or any other common privacy extensions either, I tested for that.

The strange part is that occasionally the captchas would load and function properly, although this was rare enough to make use unrealistic.

**Comment by zackultimate** [comment]
Yeah same issues it.

Disabling 4chan x make it work again.

**Comment by qwertyashes** [comment]
I've found that it seems this Captcha error comes from the interaction between TamperMonkey and 4chan X. At least on my machine.
Updating to the BETA branch of TamperMonkey solved the Captcha issue. This however did break the time formatting part of 4chan X, but thats something to be expected using a BETA branch of the loader.

**Comment by qwertyashes** [comment]
I believe that the issue is from the interaction between 4chanX and the .js loader.
I was using TamperMonkey to load my scripts and I was finding that I could disable and renable the loader to get the Captchas to work properly. I have since switched to loading using GreaseMonkey and have found that I no longer get any Captcha issues.
