### ISSUE TITLE
Remove /qa/ move note

### ISSUE THREAD

**Issue by bakugo** [ccd0/4chan-x#2671]
>If you wish to contact mods, use feedback or IRC

This text is deceiving and is leading people to waste their time doing what it says, as seen [here](https://desuarchive.org/qa/thread/3360343/#3360712).
Nobody reads feedback and bringing up site issues in IRC leads to a ban since it's a glorified ERP chatroom nowadays.

**Comment by ccd0** [comment]
They aren't getting what they want, but they're not wasting their time either. Interrupting the mods' furry ERP session shows people why they will never get what they want, at least from 4chan. And getting banned from their IRC channel is not something to worry about since they don't have your real IP, only the Rizon admins do, so it can't lead to a ban anywhere else.
