### ISSUE TITLE
Titles for embeding YouTube videos all showing the same thing

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#2893]
For a few months now the titles for YouTube embed links are all showing the same thing, I updated 4chan x and it is still the same?
![Screenshot_2021-01-10 (207) tv - Are american parties really like this - Television Film - 4chan](https://user-images.githubusercontent.com/5096684/104114915-54810800-5355-11eb-9590-7a41aa6cca29.png)

**Comment by libjared** [comment]
Youtube linkify gets the video title [on this line](https://github.com/ccd0/4chan-x/blob/7742edd22c16d737c1eff1a8389a4f984f505ca4/src/Linkification/Embedding.coffee#L511) from a service called Noembed. This service doesn't seem to be working for all videos.

[Gangnam Style - doesn't work](https://noembed.com/embed?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9bZkp7q19f0)
[Never Gonna Give You Up - works](https://noembed.com/embed?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdQw4w9WgXcQ)

Noembed may no longer be maintained, since 2017. There are old [issues on their repo](https://github.com/leedo/noembed/issues) complaining about similar problems for other providers (Imgur Facebook etc).
