### ISSUE TITLE
unknown reproduction; filtering sometimes causes it to go rogue and delete all posts

### ISSUE THREAD

**Issue by nipapi14** [ccd0/4chan-x#3246]
I have often noticed that sometimes after adding posts to the filter (since some people spam copypasta on 4chan relentlessly) 4chan x will often then just go rogue, and then proceeds to delete the entire thread's worth of posts except for my own if I made any within the thread.
It then enacts this site-wide until I force it to reset the settings with a backup copy of the settings, in which case it'll become 'stable.' I've also noticed this after adding unique IDs to the filter usually by mistake. I also noticed it once when I set 4chan x to filter any stubs and in that case I had to make my set-up from scratch.

I do not know what is absolutely necessary to reproduce this, but whatever the case is the result is always the same: whatever happens, the plugin will then delete all posts besides my own, the thread will look like it's at a low number, and all the posts are invisible site-wide across all threads once entered.

I'm on brave on windows 7 if that means anything

**Comment by gir489** [comment]
@nipapi14 Are you fucking serious? Do you even know what board this fucking plugin is for?! If mean words upset you, bro I got a better website for you. It's www.reddit.com, OK? Just go there instead, everyone is nice there. @ccd0 abandoned the project, or at least is on an indefinite hiatus. Look at all the tickets opened that aren't getting his attention since at least early 2021. Even if he was, do you really think you gave him enough to go off of?!

>AY LADS RETARD HERE IT DOESN"T WORK NO IDEA HOW TO REPRODUCE BUT UHHHH FIX PLEASE?

No, I seriously doubt that, consider I'm 24/7 addicted to this board, and when I'm not sleeping, I sit on this Mongolian basket weaving forum jerking off all day. I guarantee you I've clocked more runtime in my 2 weeks than you have in your entire lifetime on this website considering your fucking room temperature IQ knowledge of 4chan, fucking kek.

Vacuous beyond fucking belief. It's no wonder you fucking use Brave, because you're anything but.

**Comment by nipapi14** [comment]
reddit banned me off several of its boards, nice my ass. 4chan's attitude is something I'm aware of but that doesn't warrant snark elsewhere. If you can get away with saying something nasty as a nobody then it should stand to reason you wouldn't create a persona out of that if you didn't want to be disingenuous. Anonymity, after all.

I gave enough evidence about the result because I don't know how to reproduce the result, but the result is always the same. You never done a math equation of that kind before? It may have something to do with filtering, but I don't know for sure. Because of the variable amount of time as to when the bug begins to strike, staying silent about it wasn't going to fix it. There's a definitive result, and a plausible set of things that could cause it. You're grossly oversimplifying for clout points. Because that's not what I said, and I wouldn't even have started this issue if I had absolutely nothing to say about the issue at all. I make mods for other games; I'm well aware if kids state issues without going in depth on them. This is far from that and you know it.

Nice projection, bucko. You and I both know that wouldn't be true even if you wanted to feel superior about that fact. I don't know what boards you frequent but this I guess is why some are attracted to the site hmm? Guess I should be glad I'll never find out who you are c:

Just because one thing is repeated everywhere does not mean it's legitimate. Or it's the only legitimacy. Brave's a real browser as much as any. If it works, it works. Functionally otherwise, I haven't seen a difference with any other browser in regards to these things.

**Comment by gir489** [comment]
HAHAHAHAHAHA! I fucking knew you were a god damn redditor. If you use that site unironically you need to go back faggot. Cool argument, except this is a 4 FUCKING CHAN PLUGIN! Just because we're on GitHub, doesn't mean we need to all act like IT dick sucking faggot retards, because we're trying to le build the future of browser extensions. Clearly I'm NOT anonymous though, my name is right there in the corner, a few google searches and you could find out who I am and what boards I visit right quick. I seriously doubt you'd care though, because if I upset you enough to look up who I am, then you've already lost. 

What evidence?! You have no logs, no screencaps, no videos, NOTHING! Anecdotal evidence does not a case make, faggot. You're talking to someone who does K-means clustering for a living, I eat equations for breakfast. Just found out you're a /sci/ faggot though, nice job outing yourself. Here's a fucking idea POST YOUR FUCKING REGEXS AND SETTINGS FAGGOT!!!! Give me something to go off so I can help you instead of just "WAHHHH HELP ME ANONS! PLZZZZZZZZZZZ! MY BIG BRAVE BROWSER DOESN'T WORK! :(:(:(:(:(:(:("

**Comment by gir489** [comment]
Nothing is stopping you from making a new account and going back, which you should 100% do. If you look up my plebbit account it has something like 14K karma from trolling r/tf2 with my cheat and making them seethe, shitposting on r/dankmemes when it used to be popular, and hotposting on r/coontown when that shit was at its peak. God I fucking miss it... There was a time when Reddit used to be cool. The only one that's seething here is you, because you're too fucking stupid to give me what I asked for, you only gave me the settings. I asked for your RegExs too, do you even know what that means? You're so afraid that I'll find out what copypastas you filter and counter it?! Are you seriously that fucking paranoid? You're a /sci/ faggot but aren't into RegEx and JSON? You couldn't post your JSON settings, you have to make me manually go through each checkbox and see what settings correlate to what in the code?! Wow dude. Fucking wow. I remember when you guys solved an unsolvable number theory problem because one of you wanted to jerk off to some anime show or something and even got a fucking paper written about it. "Anon solves number theory" fucking kek. But now you're telling me you don't even know about common PERL CGI text expressions?! Jesus tap dancing FUCKING christ dude!

Wow dude. You don't have Shadowplay running in Instant Replay mode? That's how I've caught all my bugs that I reported here that required video evidence. Sorry, I guess my actual experience in science and technology taught me to always record myself in case a rare bug occurs, because it may never happen again. If you actually LOOKED at my profile, you'd know that isn't my fucking page, it's a fork I did, because my brother asked me to fix the mod because the OP of it was a faggot and couldn't fix it. Check the commit log instead of just clicking my profile once, seeing the Struts package I fixed once for a client a million years ago, and some Skyrim repo that I don't even maintain anymore. If you ACTUALLY looked into me, you'd know I'm a reverse engineer (says it in my profile) and I maintain the SigMaker 7.0 plugin. And to answer your latter question, I DO enjoy laughing, I made a Twitter post that went something like "If you're as happy as Apu is and getting dopamine highs off laughing, then what the fuck are you even doing with your life?! Take the stick out of your ass and come join the fun, the view is great from up here." You're telling me you got a stick so far up your ass you can't laugh at everything? Jesus fucking christ, depressed faggots need the rope. Get off my board, you don't belong.

**Comment by gir489isthebest** [comment]
OH NO GUYS! HE BLOCKED ME AGAIN! DAMN I HOPE I DON'T MAKE YET ANOTHER ACCOUNT ON A RESIDENTIAL VPN AND BYPASS GITHUB'S AUTOMATED FILTERING YET AGAIN AND MAKE HIM SEETHE AT ME AGAIN!!!! Go dilate you fucking faggot. (You) have NO fucking idea the wrath you've just fucking unleashed by pissing me off, dude. You're lucky I have to go to bed and go to work tomorrow so this will be the last post. I hope you fucking shove your Brave browser up your god damn ass, you fucking faggot. You will never be a developer. I am superior to you, fucking get over it. Seethe.

**Comment by nipapi14** [comment]
It's commented out. But sure, I'm missing the link.
I'll post if I have video, and under no other circumstances. You've contributed enough, thank you, you're not a developer here, so you don't have any business in this conversation.
Go somewhere else for your antics please. Don't think it's healthy to stalk me for no other reason.
