### ISSUE TITLE
[Question] Does anyone have the JS needed for only quote threading? 

### ISSUE THREAD

**Issue by deltabravozulu** [ccd0/4chan-x#3249]
Hi. I'm trying to strip the 4chan-x userscript down to just implement quote threading and no other features. 

Does anyone happen to have a stripped down script for this and/or could someone help to strip it down? 

The code has been relatively monolithic for a while, so finding what to keep and what to get rid of has proven challenging. None of my implementations to create this modular piece have worked thus far.

**Comment by gir489returns** [comment]
Why? What's the point? Just turn off the other features you don't want? The only thing you can't turn off is the stylizing and formatting. All your projects are in JS or Python, so I guarantee you have no real world experience in how programming actually works, but this project is tightly coupled to changing the fundamental nature of how 4chan works in your browser. Basically nothing is even left from the original 4chan code downloaded from their site. This isn't a simple staple-on for internet funny imageboard 4channel.org that you can play Jenga with until you get the result you want. This is basically a complete rewrite. You'd know that if you actually took the time to look at the fucking source code instead of just asking for a hand out. Go back to /g/ dude and take your Rust programming language with you.

**Comment by deltabravozulu** [comment]
Pretty cringe response. 

Anyway, I'm trying to strip the 4chan-x userscript down to just implement quote threading and no other features.

Does anyone happen to have a stripped down script for this and/or could someone help to strip it down?

The code has been relatively monolithic for a while, so finding what to keep and what to get rid of has proven challenging. None of my implementations to create this modular piece have worked thus far.

**Comment by gir489returns** [comment]
![1644099502929](https://user-images.githubusercontent.com/100792176/156867532-871ba25c-f431-48af-913e-dac7ebda9dea.jpg)
>Pretty cringe response.

>Anyway, I'm trying to strip the 4chan-x userscript down to just implement quote threading and no other features.

>Does anyone happen to have a stripped down script for this and/or could someone help to strip it down?

>The code has been relatively monolithic for a while, so finding what to keep and what to get rid of has proven challenging. None of my implementations to create this modular piece have worked thus far.

>Please do it for me anons because my fake-job at (((Google))) that I totally have doesn't afford me the time to do it myself!

**Comment by saxamaphone69** [comment]
Here's the `.coffee` file: https://github.com/ccd0/4chan-x/blob/master/src/Quotelinks/QuoteThreading.coffee
And the compiled JS version is around line 26625.

**Comment by deltabravozulu** [comment]
Thanks!
