### ISSUE TITLE
Fork contributions (Proposal: Change from fork to standalone repository)

### ISSUE THREAD

**Issue by m3hr** [ccd0/4chan-x#329]
Consider notifying GitHub that your fork is pretty much split from the original 4chan x so you can get contribution credit on the site? Just a thought for you, I dunno if you had considered it. Thanks!

**Comment by ccd0** [comment]
Are there any objections to this?

**Comment by qbb** [comment]
Mayhem used to have a forked repo from aeosynth.
I think he got his own after a major refactor and restructure (v3)
Maybe you could do the same? Maybe memory efficient could be the goal? Make everything simpler?

**Comment by ccd0** [comment]
I don't think I need anyone's approval for this; after all, if I wanted to, I could just recreate the repository.  The reason I'd ask Github support to do it is to preserve the issue tracker.  I'm certainly not going to do a major refactor just so people can get contribution credit on Github's stats pages.

The only disadvantage I can see to doing this is that it would make pull requests to/from other forks more difficult, but all of the forks that would be affected by this (pretty much only @ihavenoface) are dead now as far as I can tell.

And it's not as if the "is a fork of" metadata serves as a useful record of history.  If anything, it's misleading as it shows Seaweed's fork descending directly from Aeosynth's original version rather than from Appchan X.

**Comment by ccd0** [comment]
And it's done.
