### ISSUE TITLE
Support for 4MB Webm files.

### ISSUE THREAD

**Issue by CharAznableLoNZ** [ccd0/4chan-x#3324]
Recently mootwo upped the file size limit for webms to 4MB for boards that do not allow sound.

**Comment by CharAznableLoNZ** [comment]
![image](https://user-images.githubusercontent.com/2172796/213895161-5f1a7023-097d-4b34-8b75-3f90f643825f.png)

**Comment by saxamaphone69** [comment]
4chan X grabs the maximum file size of WEBMs from the `boards.json` API I believe. That hasn't been updated since August 2022.
The small amount of JS in the `<head>` seems to have updated, which is what 4chan/the native 4chan extension grabs from.

Old:
`<script type="text/javascript">var style_group = "ws_style",cssVersion = 710,jsVersion = 1057,comlen = 2000,maxFilesize = 4194304,maxLines = 100,clickable_ids = 1,cooldowns = {"thread":600,"reply":60,"image":60};var unique_ips = 1;var maxWebmFilesize = 3145728;var board_archived = true;var t_captcha = true;var check_for_block = 1;var danbo_rating = '__SFW__';var danbo_fb = {"t_bg":"176,1,5050,5f599fefc6c73,176,2,470,5f59a00f01673","b_bg":"176,1,5078,5f5ef92eec034,176,2,5079,5f5ef93fac7ed"};</script>`

New:
`<script type="text/javascript">var style_group = "ws_style",cssVersion = 710,jsVersion = 1057,comlen = 2000,maxFilesize = 4194304,maxLines = 100,clickable_ids = 1,cooldowns = {"thread":600,"reply":60,"image":60};var board_archived = true;var t_captcha = true;var check_for_block = 1;var danbo_rating = '__SFW__';var danbo_fb = {"t_bg":"176,1,5050,5f599fefc6c73,176,2,470,5f59a00f01673","b_bg":"176,1,5078,5f5ef92eec034,176,2,5079,5f5ef93fac7ed"};</script>`

Perhaps [asking for the API to be updated](https://github.com/4chan/4chan-API/issues) might help.

**Comment by CharAznableLoNZ** [comment]
Good point.  I looked through the script and couldn't find where it was defined so it makes sense it's getting the value from the API.
