### ISSUE TITLE
New version requires multiple tabs to reach captcha from post

### ISSUE THREAD

**Issue by Misterdark** [ccd0/4chan-x#333]
The old version only required a single tab and after updating it requires 3 tabs presses now. Is this a bug or just working as intended?

**Comment by ccd0** [comment]
It's a change on Google's end and is a problem with all Recaptchas
https://www.google.com/recaptcha/api2/demo
so it needs to be fixed on Google's end.  I think
https://groups.google.com/forum/#!forum/recaptcha
might be the place to complain.

In order to fix this in 4chan X, I'd need to have the script run on the captcha iframe page, which is something I've been loath to do for fear of making users look more like bots.

**Comment by Misterdark** [comment]
Alright just wanted to know. Thanks for the heads up.

**Comment by ccd0** [comment]
I decided to go ahead and run on the captcha iframe page.  Those extra tabs were awful.  I've tried to avoid doing anything if the captcha is checked it with the mouse.

**Comment by Farfie** [comment]
Hey guys, I noticed that when I re-enabled flash, it only took me one tab to get to the captcha. This was on Firefox Dev. Maybe this is a clue of some kind?

**Comment by ccd0** [comment]
@Farfie

Enabling / disabling Flash doesn't seem to make a difference for me.

**Comment by Farfie** [comment]
Yeah sorry, you must have pushed an update at the same time I was reporting.
