### ISSUE TITLE
Where does 4chanx store its data in firefox on win7?

### ISSUE THREAD

**Issue by Maoman1** [ccd0/4chan-x#3415]
I am trying to restore settings which I forgot to export before upgrading to 10, but I still have all the files from the old windows installation so I just need to know where they are please. I could not find the info in any other post.

**Comment by saxamaphone69** [comment]
#3404

**Comment by Maoman1** [comment]
> in firefox on win7?

**Comment by saxamaphone69** [comment]
I'll just lock this and you can respond to me in the original issue.

In case you missed it, I asked as a userscript or extension, and then offered a solution about temporarily importing your old profile, which you say you have, exporting what you need, then you can delete it again.

Since you *now* say you use Firefox, then it must be a userscript, as the extension is not from here, to which I offered 2 links to aid you in your attempt to get your stuff back.
