### ISSUE TITLE
Switched from Chrome to Firefox - Unable to go to next Webm/Photos in Gallery Mode 

### ISSUE THREAD

**Issue by thegattsu** [ccd0/4chan-x#3435]
[SYMPTOM] - When in Gallery mode, clicking on the video or picture will only pause/start the video. When using the same extension with the same settings in Chrome, clicking on the video or picture while in Gallery mode will go to the next webm/picture. The only way to go to the next webm/video is by clicking on the thumbnails on the side of the screen. For years, I've been clicking on the image/video itself in the player while in Gallery mode.

I've downgraded to multiple version but can't seem to get the gallery to function the same way in Chrome in Firefox.

Running TamperMonkey 5.0.1 and the current version of 4chanX

**Comment by saxamaphone69** [comment]
Interesting, this 'bug' has been in [Firefox for 12 years](https://bugzilla.mozilla.org/show_bug.cgi?id=693014).

Not that it totally fixes the problem, but in the Settings if you turn off 'Show Controls', then it goes to the expected behaviour. Then if you do need the controls, you can right click the video.

Otherwise, there should be the 'previous' and 'next' buttons to the left and right of the Gallery that will go back and forth, regardless of the 'Show Controls' setting.

**Comment by thegattsu** [comment]
> Interesting, this 'bug' has been in [Firefox for 12 years](https://bugzilla.mozilla.org/show_bug.cgi?id=693014).
> 
> Not that it totally fixes the problem, but in the Settings if you turn off 'Show Controls', then it goes to the expected behaviour. Then if you do need the controls, you can right click the video.
> 
> Otherwise, there should be the 'previous' and 'next' buttons to the left and right of the Gallery that will go back and forth, regardless of the 'Show Controls' setting.

Holy crap. Thank you so much for this. I've been suffering with this bug for so long.
