### ISSUE TITLE
certain threads aren't loading

### ISSUE THREAD

**Issue by oluapris** [ccd0/4chan-x#381]
Occasionally when I open a thread, it doesn't actually load and my laptop gets really hot. The page in question also doesn't close for a few seconds after I click close. It sometimes happens to threads I already have open too.

**Comment by ccd0** [comment]
Can you link to a thread where this happens?  More detail would help:
https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md

**Comment by oluapris** [comment]
http://boards.4chan.org/v/thread/290788752#p290788752
Sorry I'm late, but this doesn't happen too often.

**Comment by ccd0** [comment]
Does it happen every time you load that thread?  Can you post your browser and exported settings?  Are you using any extensions?  Basically everything from https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md would be helpful as I'm not seeing the issue on my end.

**Comment by oluapris** [comment]
I'm using Chrome version 41.0.2272.118 m, 4chanX version 1.10.8.10 (settings: http://a.pomf.se/qymvzs.json), and OneeChan version 5.5.25 (settings: http://a.pomf.se/cdbmpn.json). The problem happened whenever I load the thread with 4chanX on, but when i turn it off the thread loads just fine.

**Comment by ccd0** [comment]
Looks like the problem is your comment filter
`/.*(a+\W*)+(y+\W*)+\W*l\W*m\W*f?\W*a\W*o.*/i`
which when it encounters something like the "AYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY" at https://boards.4chan.org/v/thread/290788752#p290790701 tries to test every possible way of splitting the Y's up into groups. You can fix it by changing it to:
`/.*a[a\W]*y[y\W]*l\W*m\W*f?\W*a\W*o/i`

**Comment by oluapris** [comment]
It worked. Thanks!
