### ISSUE TITLE
Clarify that archives are not 4chan

### ISSUE THREAD

**Issue by fgts** [ccd0/4chan-x#404]
The archive report feature is very helpful in getting CP and stuff reported to us, but it also draws in a ridiculous amount of reports for stuff that should be reported to 4chan instead. [Even after pointing it out](https://a.pomf.se/hwbvlu.png), it still goes ignored.

I'd like to suggest doing something about the link injected into the report window. I was thinking changing the label to "Report to archive" (instead of the name) may or may not help, and/or also only displaying the link if the spam/illegal content radio button is selected. Mind sharing your thoughts?

**Comment by ccd0** [comment]
I would imagine more people are coming in through the redirect after they submit the report to 4chan than through the link.  I've fixed the redirect to only happen for spam and rule violation reports.  The link completely bypasses reporting to 4chan (I imagine some people might not want to bother with the captcha), so I don't think it makes sense to hide or show it based on the category selected.

I've seen the message, but it doesn't show up all the time.  It looks like you're only showing it if the referrer is from 4chan, which means it doesn't show for reports of already deleted posts (which I'm sending directly to the archive page), or for anyone who has referers blocked..  You might want to show the message every time, since I don't think there are many people using that interface except from 4chan.  And maybe you could put the word "archive" somewhere in a larger font.

**Comment by fgts** [comment]
Oh, I was not aware that there was a redirect after reporting to 4chan. That change alone should definitely help; thank you!
