### ISSUE TITLE
"No valid captcha" error for quick reply function

### ISSUE THREAD

**Issue by Question2** [ccd0/4chan-x#412]
This has been happening constanty. Ive tried reinstalling the extension and restarting firefox 38.0.1 but it doesnt help.

When i try to use the quick reply function, i can solve the captcha and get the green tick mark, but then the post refuses to submit. Clicking submit again simply gives the error "No valid captcha" even though the green check mark is there. Trying to solve the captcha again doesnt help.

**Comment by ccd0** [comment]
> the post refuses to submit.
More details?  Are there any error messages?  Anything in the browser console?  Have you tried disabling other extensions to check for a conflict?

> Clicking submit again simply gives the error "No valid captcha" even though the green check mark is there.
I have the green check mark disappear on a timer, so it may still be there even if you've used the captcha already.  To make it less confusing, I'll change it so it disappears immediately when all captchas are used, but for now, look at the "Captchas: #" line instead of the checkbox.

**Comment by Question2** [comment]
Theress no error messages until i try clicking submit again and the "no valid captcha" message pops up.

I dont have any other extensions that interact with 4chan....im not sure how to check the browser console on firefox.

The quick reply box always says : captchas : 0 even though i just solved the captcha.

**Comment by ccd0** [comment]
>I dont have any other extensions that interact with 4chan

You can't know that without testing it.  Turn them all off, and see if you still have a problem.  Alternately, create a new profile and see if 4chan X works on it.

>im not sure how to check the browser console on firefox.

Press Control+Shift+J.  Look for messages that appear when you try to post and fail.

>The quick reply box always says : captchas : 0 even though i just solved the captcha.

Does it say that after solving the captcha but before the *first* time you click the submit button?

**Comment by ccd0** [comment]
Is this still happening?
