### ISSUE TITLE
noscript captchas no longer load

### ISSUE THREAD

**Issue by Royerson** [ccd0/4chan-x#423]
With "Force Noscript Captcha" enabled nothing happens when moving to the captcha box; the captcha never loads. Tried turning on "Auto-load captcha" and still wouldn't work.

So now the only way to post is by disabling noscript captchas and clicking (CLICKING!) breads for google's hivemind. Would really appreciate it if you could fix it.

**Comment by hotdogman** [comment]
Are you using the latest version? This is the noscript captcha with 4chan X beta v1.11.0.3. You'll still have to play Google's "Find the Food" game.
![screenshot113](https://cloud.githubusercontent.com/assets/4343306/8265970/b2906ec8-16d8-11e5-9666-227c8f398997.png)

**Comment by ccd0** [comment]
Make sure you're up to date.  In both v1.10.14.4 (stable version) and v1.11.0.3 (beta version), the non-Javascript version of the captcha should load.  Unfortunately, it is an image selection captcha.  As far as I can tell, Google has now done away with text captchas in Recaptcha v2.

If your concern is keyboard navigability rather than running Google's Javascript, the box can be checked with the space bar, and the image selection captcha is navigable by the arrow keys / IJKL provided you have `Captcha Fixes` turned on (which it is by default).  You don't have to click on anything.

**Comment by Royerson** [comment]
Welp, RIPeronis.

Google wins, time to embrace the botnet.
