### ISSUE TITLE
captcha window bug

### ISSUE THREAD

**Issue by CouldBeWhat** [ccd0/4chan-x#433]
if you click on the captcha tick and try to copy paste an image link to the file section while the captcha images are still open, the captcha image window disappears.

**Comment by ccd0** [comment]
I don't think there's anything I can reasonably do about that.  Google deliberately hides the image selection popup when it loses focus, and it makes sense to do so in general because it could be blocking stuff.  You can bring up the popup again by re-clicking on the checkbox.  Any images you have selected should still be there.  Alternatively, if you don't like how the image selection captcha works, you can switch to `Use Recaptcha v1` in your settings.
