### ISSUE TITLE
Infinite scrolling skips pages (was: Dissable infinite scrollig but keep JSON navagation)

### ISSUE THREAD

**Issue by stealer0517** [ccd0/4chan-x#434]
An option to disable infinite scrolling would be great since 4chanx periodically freaks out and skips a few pages instead of loading the next one.

**Comment by ccd0** [comment]
The option is at the top of the index, in the drop-down menu just above the first thread.
What specifically are you doing (i.e. what are you turning/clicking/dragging) when the page-skipping bug happens?

**Comment by stealer0517** [comment]
I’m just scrolling like normal.

**Comment by ccd0** [comment]
@stealer0517
There are lots of perfectly normal ways of scrolling a document.  Are you using the mouse wheel, the scroll bar, the arrow keys, etc.?

**Comment by stealer0517** [comment]
Two finger scrolling in mac os (firefox)

**Comment by ccd0** [comment]
Was the problem just skipping past stuff when scrolling, or were there any missing threads?

**Comment by stealer0517** [comment]
about 5 or so threads would go missing.

**Comment by ccd0** [comment]
Thanks for clarifying.  I took another look and found a bug where you scrolled down to page 2, then changed some settings such as the index sort order or whether to show replies, it would cut the index down to one page but not clear the old page count, so that if you scrolled down again it would show pages 3, 4, and so on.  This should be fixed as of the latest beta (v1.11.8.2).  Let me know if you still see problems.
