### ISSUE TITLE
Option to open links in custom header in new tab

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#504]
From https://github.com/ccd0/4chan-x/issues/500#issuecomment-145739221:

Is there a way to format the custom header tags on an external link to make it open in a new tab when clicked?

**Comment by saxamaphone69** [comment]
Not sure if some of the issues that [this](https://medium.com/@ali.dev/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f) and [this](https://blog.dareboost.com/en/2017/03/target-blank-links-rel-noopener-performance-security/) article bring up concern us here, but I had a go at this one too.

In `Header` you can change:
`L91` to `re = /[\w@]+(-(all|title|replace|full|index|catalog|archive|expired|nt|(mode|sort|text):"[^"]+"(,"[^"]+")?))*|[^\w@]+/g`
where `-nt` denotes new tab, and then after the `expired` test, add:
```
if /-nt/.test t
  a.target = '_blank'
  a.rel = 'noreferrer noopener';
  return a
```

**Comment by ccd0** [comment]
>Not sure if some of the issues that this and this article bring up concern us here

It would probably be a good idea to go around the 4chan X codebase and systematically add `rel=noopener` where there's `target=_blank` if only for the performance reasons.

**Comment by saxamaphone69** [comment]
Manually, or through the build process?

If manually, I could do it (doesn't seem like that [many instances](https://github.com/ccd0/4chan-x/search?q=_blank&unscoped_q=_blank)). Then it would just become expected practice that any new code follows this. Would you want `noopener` and `noreferrer`? Or just `noopener`?

Build process-wise, no clue how to code that.

FWIW, on my machine, [I notice no jank/lag](https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/) because all the big boy browsers in 2019 are multi-threaded.

As for the issue at hand, I can make a PR. Are you happy with `-nt` denoting new tab? It would be documented in the Custom Board Navigation advanced section, of course. `-opennew`?

**Comment by ccd0** [comment]
> Manually, or through the build process?

I mean manually.

> Would you want `noopener` and `noreferrer`? Or just `noopener`?

As I see it, `noreferrer` would be a separate issue unrelated to `target="_blank"`. I'd have to think about where it would be appropriate to add it. I'm not sure it makes sense to go around the codebase systematically adding it to every link, and if we decided we wanted it on every link, that might be better accomplished by a referrer policy.
