### ISSUE TITLE
Captchas not applying.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#522]
Submitter: Duke
Email: dbeaconsfield@aol.com
My captchas aren't actually working.
I click the street signs, or french fries, or whatever, and it gives me the checkmark, then tells me that I don't havea  valid captcha.
Even if it reads "Captcha: 1"
So I'm not sure the problem.

**Comment by ccd0** [comment]
Could you give more details?  See
https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md#reporting-bugs
A screen capture of what you're doing might also help.

**Comment by Duke-of-Beaconsfield** [comment]
Apologies! First time reporting a bug. Well, alright. So I checked for errors, and there's a whole whole lot, I guess.
Went ahead and screencapped that for your viewing pleasure.
Also a screencap of what happens when trying to post.
As far as I know I'm not doing anything differently than I was doing before just a few days ago when this started.
I've cleared the cache and my cookies, and reinstalled 4chan X and checked for updates, and that's just about the extent of my knowledge of what to do in these situations.
If you need any more info, let me know.
Thank you!

![oh boy thats a lotta errors](https://cloud.githubusercontent.com/assets/15118281/10474853/e1e08262-71f0-11e5-8784-6316f73551f3.png)
![what happenes](https://cloud.githubusercontent.com/assets/15118281/10474854/e7c8ec00-71f0-11e5-9753-444cf5bf7591.png)

**Comment by ccd0** [comment]
It looks like the NS_ERROR_STORAGE_BUSY error, whatever that is, is keeping 4chan X from saving the code from the captcha.  Does it happen in a fresh Firefox profile?

**Comment by ccd0** [comment]
Is this still a problem?
