### ISSUE TITLE
Firefox + 4chan X after a recent update loads 4ch very slow with constant hard freezes

### ISSUE THREAD

**Issue by HASJ** [ccd0/4chan-x#719]
I've always used 4chan X with Firefox but as far as two weeks ago, loading 4chan pages with 4chan X enabled is painfully slow. It can take 10 up to 60 seconds until I can click on Firefox again. The worst freezes happen in catalog mode.

Resetted settings, nothing.
Disabled everything except GreaseMonkey and 4chan X, nothing.

**Comment by ccd0** [comment]
Does it happen in a fresh profile?
What about with older versions of [4chan X](https://github.com/ccd0/4chan-x/blob/master/CHANGELOG.md), [Greasemonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/), and [Firefox](https://ftp.mozilla.org/pub/firefox/releases/)?

**Comment by HASJ** [comment]
>Older versions
>4chan X
I went back up to 1.11.19 and updated all the way to the most recent and it seems to be gone. Shit like this is so stupid.

**Comment by ccd0** [comment]
Not sure what would cause that. Perhaps a botched download of the script? May not even be 4chan X related, but good to hear it's working now. Let me know if it becomes a problem again, I guess.

**Comment by tjohnman** [comment]
I've been experiencing this for as long as I can remember, on Windows, macOS and Linux. I'm currently using Firefox 52.0.2 and 4chan X 1.13.8.5, but as I said, I've been seeing it forever. I blame Firefox for not being as well optimized as Chrome, but I wonder if some tweaks could be done to the script to make it work better on this browser.

Whenever I open a new 4chan tab in catalog view, the browser freezes completely for up to 15 seconds. I think this is because there's a lot of DOM parsing and styles being applied (perhaps it has something to do with the amount of images, as it performs noticeably better in index view).
I attach a performance profile. In case it's useful.

[profile.json.zip](https://github.com/ccd0/4chan-x/files/889578/profile.json.zip)

**Comment by tjohnman** [comment]
OK, it seems this is Firefox's fault (or perhaps Greasemonkey's) because it happens with 4chan X disabled.
